site_name: 扁鹊项目文档
pages:
- 简介 : index.md
- 应用模块 : 
    - aliyun : aliyun.md
    - report : report.md
    - query  : query.md
    - check  : check.md











markdown_extensions:                                                                   
    - toc:
        permalink: 
    - admonition
    - def_list






#theme: readthedocs
