site_name: 扁鹊项目文档
pages:
- 扁鹊 : index.md
- 应用 : 
    - 扁鹊 : bianque.md
    - 扁鹊client : bianque_client.md




markdown_extensions:                                                                   
    - toc:
        permalink: 
    - admonition
    - def_list






#theme: readthedocs
